### ISSUE TITLE
请问如何运行？原lab来自哪里？想要搜这个lab的其他相关参考应该搜什么关键词？

### ISSUE THREAD

**Issue by TTTTTTi** [labyrinth-ssr/HDFS-Corba#1]
我在运行testclient.java时出现问题：
org.omg.CosNaming.NamingContextPackage.NotFound: IDL:omg.org/CosNaming/NamingContext/NotFound:1.0
	at org.omg.CosNaming.NamingContextPackage.NotFoundHelper.read(NotFoundHelper.java:72)
	at org.omg.CosNaming._NamingContextExtStub.resolve_str(_NamingContextExtStub.java:165)
	at impl.ClientImpl.run(ClientImpl.java:195)
	at client.TestClient.main(TestClient.java:10)
所以我注释了run里的3个对象的新建，只留下了一个就可以运行了
但是在输入open xxx.txt r后就会报错：
十月 21, 2023 5:10:54 下午 com.sun.corba.se.impl.transport.SocketOrChannelConnectionImpl <init>
警告: "IOP00410201: (COMM_FAILURE) Connection failure: socketType: IIOP_CLEAR_TEXT; hostname: xxx; port: 62547"
org.omg.CORBA.COMM_FAILURE:   vmcid: SUN  minor code: 201  completed: No
	at com.sun.corba.se.impl.logging.ORBUtilSystemException.connectFailure(ORBUtilSystemException.java:2200)
	at com.sun.corba.se.impl.logging.ORBUtilSystemException.connectFailure(ORBUtilSystemException.java:2221)
	at com.sun.corba.se.impl.transport.SocketOrChannelConnectionImpl.<init>(SocketOrChannelConnectionImpl.java:223)
	at com.sun.corba.se.impl.transport.SocketOrChannelConnectionImpl.<init>(SocketOrChannelConnectionImpl.java:236)
	at com.sun.corba.se.impl.transport.SocketOrChannelContactInfoImpl.createConnection(SocketOrChannelContactInfoImpl.java:119)
	at com.sun.corba.se.impl.protocol.CorbaClientRequestDispatcherImpl.beginRequest(CorbaClientRequestDispatcherImpl.java:187)
	at com.sun.corba.se.impl.protocol.CorbaClientDelegateImpl.request(CorbaClientDelegateImpl.java:137)
	at org.omg.CORBA.portable.ObjectImpl._request(ObjectImpl.java:449)
	at api._NameNodeStub.open(_NameNodeStub.java:18)
	at impl.ClientImpl.open(ClientImpl.java:48)
	at impl.ClientImpl.run(ClientImpl.java:235)
	at client.TestClient.main(TestClient.java:10)
Caused by: java.net.ConnectException: Connection timed out: connect
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:459)
	at sun.nio.ch.Net.connect(Net.java:451)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:646)
	at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
	at com.sun.corba.se.impl.transport.DefaultSocketFactoryImpl.createSocket(DefaultSocketFactoryImpl.java:95)
	at com.sun.corba.se.impl.transport.SocketOrChannelConnectionImpl.<init>(SocketOrChannelConnectionImpl.java:207)
	... 9 more

org.omg.CORBA.COMM_FAILURE:   vmcid: SUN  minor code: 201  completed: No
	at com.sun.corba.se.impl.logging.ORBUtilSystemException.connectFailure(ORBUtilSystemException.java:2200)
	at com.sun.corba.se.impl.logging.ORBUtilSystemException.connectFailure(ORBUtilSystemException.java:2221)
	at com.sun.corba.se.impl.transport.SocketOrChannelConnectionImpl.<init>(SocketOrChannelConnectionImpl.java:223)
	at com.sun.corba.se.impl.transport.SocketOrChannelConnectionImpl.<init>(SocketOrChannelConnectionImpl.java:236)
	at com.sun.corba.se.impl.transport.SocketOrChannelContactInfoImpl.createConnection(SocketOrChannelContactInfoImpl.java:119)
	at com.sun.corba.se.impl.protocol.CorbaClientRequestDispatcherImpl.beginRequest(CorbaClientRequestDispatcherImpl.java:187)
	at com.sun.corba.se.impl.protocol.CorbaClientDelegateImpl.request(CorbaClientDelegateImpl.java:137)
	at org.omg.CORBA.portable.ObjectImpl._request(ObjectImpl.java:449)
	at api._NameNodeStub.open(_NameNodeStub.java:18)
	at impl.ClientImpl.open(ClientImpl.java:48)
	at impl.ClientImpl.run(ClientImpl.java:235)
	at client.TestClient.main(TestClient.java:10)
Caused by: java.net.ConnectException: Connection timed out: connect
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:459)
	at sun.nio.ch.Net.connect(Net.java:451)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:646)
	at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
	at com.sun.corba.se.impl.transport.DefaultSocketFactoryImpl.createSocket(DefaultSocketFactoryImpl.java:95)
	at com.sun.corba.se.impl.transport.SocketOrChannelConnectionImpl.<init>(SocketOrChannelConnectionImpl.java:207)
	... 9 more

请问这个lab的原题来自哪里？我想要得到更多的参考资料请问应该搜索什么关键词？我已经尝试去搜索了，但是全网只找到您这一个参考，所以我真的非常需要您的答复，感谢！

**Comment by labyrinth-ssr** [comment]
fdu fhw的分布式系统概论，，
实现的话基本就是靠看漫画。。。。
https://brucemaa.cn/2021/03/hadoop-hdfs-cartoon/
这些测试，，我记得可能不能一次性过，需要在源码上改配置可能，不过当时测试也只是参考。

**Comment by TTTTTTi** [comment]
感谢回复，您能写出来真的太厉害了！请问您有写实验报告吗？可以参考一下吗，关于这个代码的运行方法和具体细节等我还是有点不太清楚...

**Comment by labyrinth-ssr** [comment]
@TTTTTTi 抱歉，完全找不到了。。你可以问问助教？
